"""
Test Orchestrator for coordinating test analysis and execution.

Note: Test generation has been moved to Copilot/AI assistants via MCP tools.
This orchestrator now focuses on analysis and execution only.
"""

import os
import uuid
import logging
from typing import List, Dict, Optional

from src.models.testing_models import (
    TestGenerationSession, 
    TestableElement, 
    TestResult,
    TestType
)
from src.testing.test_analyzer import TestAnalyzer
from src.testing.test_validator import TestValidator
from src.testing.test_runner import TestRunner

logger = logging.getLogger(__name__)


class TestOrchestrator:
    """
    Coordinates test analysis and execution.
    
    Test generation is now handled externally by AI assistants (e.g., GitHub Copilot)
    using context provided by the MCP server's analyze_testability tool.
    """
    
    def __init__(
        self,
        test_analyzer: Optional[TestAnalyzer] = None,
        test_validator: Optional[TestValidator] = None,
        test_runner: Optional[TestRunner] = None
    ):
        self.analyzer = test_analyzer or TestAnalyzer()
        self.validator = test_validator or TestValidator()
        self.runner = test_runner or TestRunner()
        
        self.current_session: Optional[TestGenerationSession] = None
        self.tests_dir = "tests"
        
    def start_session(self, files: List[str]) -> TestGenerationSession:
        """Start a new test analysis session."""
        session_id = str(uuid.uuid4())
        self.current_session = TestGenerationSession(
            session_id=session_id,
            selected_files=files
        )
        return self.current_session
        
    def analyze_selected_files(self) -> Dict[str, TestableElement]:
        """
        Analyze files in the current session to find testable elements.
        
        Returns:
            Dictionary mapping element_id to TestableElement
        """
        if not self.current_session:
            raise ValueError("No active session")
            
        for file_path in self.current_session.selected_files:
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                elements = self.analyzer.analyze_file(file_path, content)
                for el in elements:
                    self.current_session.identified_elements[el.element_id] = el
                    
            except Exception as e:
                logger.error(f"Failed to analyze {file_path}: {e}")
        
        return self.current_session.identified_elements
    
    def get_testable_elements(self) -> List[TestableElement]:
        """Get all identified testable elements from current session."""
        if not self.current_session:
            return []
        return list(self.current_session.identified_elements.values())
    
    def validate_test_code(self, test_code: str) -> tuple:
        """
        Validate syntax of test code (e.g., generated by Copilot).
        
        Args:
            test_code: Python test code to validate
            
        Returns:
            Tuple of (is_valid, error_message)
        """
        return self.validator.validate_syntax(test_code)
    
    def save_test_file(self, filename: str, test_code: str, append: bool = False) -> str:
        """
        Save test code to a file.
        
        Args:
            filename: Name of the test file (e.g., "mymodule_test.py")
            test_code: Python test code to save
            append: If True, append to existing file
            
        Returns:
            Full path to the saved file
        """
        if not os.path.exists(self.tests_dir):
            os.makedirs(self.tests_dir)
        
        save_path = os.path.join(self.tests_dir, filename)
        mode = 'a' if append and os.path.exists(save_path) else 'w'
        
        with open(save_path, mode, encoding='utf-8') as f:
            if mode == 'a':
                f.write("\n\n")
            f.write(test_code)
        
        return save_path
        
    def run_single_test(self, file_path: str) -> TestResult:
        """Run a single test file."""
        return self.runner.run_file(file_path)
    
    def run_all_tests(self) -> Dict[str, TestResult]:
        """Run all tests in the tests/ directory."""
        return self.runner.run_all(self.tests_dir)
    
    def analyze_file(self, file_path: str, content: str) -> List[TestableElement]:
        """
        Analyze a single file to find testable elements.
        
        This is a convenience method for MCP tool integration.
        """
        return self.analyzer.analyze_file(file_path, content)
