"""
cgctl init — Initialise a CodeGuardian project.

Always runs locally (no server required): creates the .codeguardian/
directory, writes a config.toml, and derives a project_id from the
directory name (same convention the server uses).
"""

from __future__ import annotations

import os
import time
from pathlib import Path

import typer
from rich.panel import Panel

from cgctl.utils.output import (
    console,
    print_error,
    print_info,
    print_success,
    print_warning,
    print_header,
    print_stats,
)
from cgctl.utils.validators import validate_project_path, sanitize_project_name

app = typer.Typer(help="Initialise a CodeGuardian project")

_CONFIG_TEMPLATE = """\
# CodeGuardian project configuration
# Generated by cgctl init

[project]
project_id = "{project_id}"
project_name = "{project_name}"
created_at = "{created_at}"
"""


@app.callback(invoke_without_command=True)
def init_project(
    ctx: typer.Context,
    path: str = typer.Argument(".", help="Path to the project directory"),
    name: str = typer.Option(None, "--name", "-n", help="Project name (defaults to directory name)"),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing configuration"),
):
    """
    Initialise a new CodeGuardian project.

    Creates a .codeguardian/ directory with a config file.
    The project_id defaults to the directory name — the same
    convention used by the FastAPI server.

    Examples:
        cgctl init
        cgctl init /path/to/project --name my-project
        cgctl init --force  # reinitialise existing project
    """
    print_header("CodeGuardian Project Setup", "Initialising project configuration")

    project_path = os.path.abspath(os.path.expanduser(path))

    is_valid, error = validate_project_path(project_path)
    if not is_valid:
        print_error(error)
        raise typer.Exit(1)

    project_name = sanitize_project_name(name or os.path.basename(project_path))
    project_id = project_name  # matches server convention: Path(project_path).name

    print_info(f"Project path: [cyan]{project_path}[/cyan]")
    print_info(f"Project ID:   [cyan]{project_id}[/cyan]")

    cg_dir = Path(project_path) / ".codeguardian"
    config_file = cg_dir / "config.toml"

    if config_file.exists() and not force:
        print_warning(
            "Project already initialised. Use [bold]--force[/bold] to reinitialise."
        )
        _show_next_steps()
        raise typer.Exit(0)

    # Create directory structure
    cg_dir.mkdir(parents=True, exist_ok=True)
    (cg_dir / "cache").mkdir(exist_ok=True)

    # Write config
    config_content = _CONFIG_TEMPLATE.format(
        project_id=project_id,
        project_name=project_name,
        created_at=time.strftime("%Y-%m-%dT%H:%M:%S"),
    )
    config_file.write_text(config_content)

    # Write .gitignore inside .codeguardian so cache isn't committed
    gitignore = cg_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text("cache/\n*.tmp\n")

    print_success(f"Created [cyan].codeguardian/config.toml[/cyan]")

    print_stats({
        "Project ID": project_id,
        "Project Name": project_name,
        "Config": str(config_file),
    })

    _show_next_steps()


def _show_next_steps() -> None:
    console.print()
    console.print(
        Panel(
            "[bold]Next steps:[/bold]\n\n"
            "  1. Start the server:  [cyan]cgctl serve[/cyan]\n"
            "  2. Index the project: [cyan]cgctl index .[/cyan]\n"
            "  3. Ask questions:     [cyan]cgctl ask \"how does auth work?\"[/cyan]",
            title="[green]Ready[/green]",
            border_style="green",
        )
    )
