"""
Core data structures and models for the Smart Code Documentation Generator.

This module defines all the dataclasses used throughout the documentation
generation workflow, including code elements, context information, documentation
items, and workflow management structures.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Optional, Tuple, Any, Callable
from enum import Enum


# ============================================================================
# Enums for Status and Types
# ============================================================================

class SessionStatus(Enum):
    """Status of a documentation generation session."""
    ANALYSIS = "analysis"
    CONTEXT = "context"
    GENERATION = "generation"
    REVIEW = "review"
    COMPLETE = "complete"
    ERROR = "error"


class ApprovalStatus(Enum):
    """Approval status for generated documentation."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EDITED = "edited"


class ElementType(Enum):
    """Type of code element."""
    FUNCTION = "function"
    CLASS = "class"
    METHOD = "method"
    MODULE = "module"


class Language(Enum):
    """Supported programming languages."""
    PYTHON = "python"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"


class DependencyType(Enum):
    """Type of dependency relationship."""
    IMPORT = "import"
    FUNCTION_CALL = "function_call"
    INHERITANCE = "inheritance"


class ErrorType(Enum):
    """Type of error encountered during processing."""
    PARSING = "parsing"
    CONTEXT_ANALYSIS = "context_analysis"
    LLM_GENERATION = "llm_generation"
    EXPORT = "export"


# ============================================================================
# Code Element Models
# ============================================================================

@dataclass
class Parameter:
    """Represents a function or method parameter."""
    name: str
    type_hint: Optional[str] = None
    default_value: Optional[str] = None


@dataclass
class CodeElement:
    """
    Represents a documentable code element (function, class, method).
    
    This is the core unit of analysis and documentation generation.
    """
    element_id: str
    name: str
    element_type: str  # 'function', 'class', 'method'
    file_path: str
    start_line: int
    end_line: int
    language: str
    code_content: str
    existing_doc: Optional[str] = None
    quality_score: float = 0.0  # 0-100
    has_gap: bool = True
    parent_class: Optional[str] = None
    parameters: List[Parameter] = field(default_factory=list)
    return_type: Optional[str] = None


# ============================================================================
# Analysis Models
# ============================================================================

@dataclass
class FileAnalysis:
    """Results of analyzing a single file."""
    file_path: str
    language: str
    code_elements: List[CodeElement]
    total_lines: int


@dataclass
class GapReport:
    """
    Report of documentation gaps across analyzed files.
    
    Generated by the Analysis Agent.
    """
    total_elements: int
    elements_with_gaps: int
    elements_by_type: Dict[str, int]
    elements_by_language: Dict[str, int]
    file_analyses: List[FileAnalysis]
    average_quality_score: float


# ============================================================================
# Context Models
# ============================================================================

@dataclass
class Dependency:
    """Represents a dependency relationship between code elements."""
    name: str
    dependency_type: str  # 'import', 'function_call', 'inheritance'
    source_element_id: str
    target_element_id: Optional[str] = None


@dataclass
class InheritanceInfo:
    """Information about class inheritance relationships."""
    parent_classes: List[str] = field(default_factory=list)
    child_classes: List[str] = field(default_factory=list)
    interfaces: List[str] = field(default_factory=list)


@dataclass
class SimilarCode:
    """Represents semantically similar code found via vector search."""
    element_id: str
    file_path: str
    similarity_score: float
    code_snippet: str


@dataclass
class ElementContext:
    """
    Contextual information about a code element.
    
    Generated by the Context Agent to inform documentation generation.
    """
    element_id: str
    imports: List[str] = field(default_factory=list)
    dependencies: List[Dependency] = field(default_factory=list)
    called_functions: List[str] = field(default_factory=list)
    accessed_variables: List[str] = field(default_factory=list)
    inheritance: Optional[InheritanceInfo] = None
    similar_code: List[SimilarCode] = field(default_factory=list)
    purpose_inference: str = ""
    complexity_score: float = 0.0


@dataclass
class DependencyGraph:
    """Directed graph of dependencies between code elements."""
    nodes: List[str] = field(default_factory=list)  # element_ids
    edges: List[Tuple[str, str]] = field(default_factory=list)  # (from_id, to_id)


@dataclass
class ContextMap:
    """
    Complete context mapping for all code elements.
    
    Includes dependency graph and processing order.
    """
    element_contexts: Dict[str, ElementContext] = field(default_factory=dict)  # element_id -> context
    dependency_graph: DependencyGraph = field(default_factory=DependencyGraph)
    processing_order: List[str] = field(default_factory=list)  # element_ids in dependency order


# ============================================================================
# Documentation Models
# ============================================================================

@dataclass
class DocumentationItem:
    """
    Generated documentation for a code element.
    
    Includes metadata for review and approval workflow.
    """
    element_id: str
    element_name: str
    element_type: str
    file_path: str
    language: str
    generated_doc: str
    format_type: str  # 'google_docstring', 'jsdoc'
    confidence_score: float
    generation_time_ms: float
    approval_status: str = "pending"  # 'pending', 'approved', 'rejected', 'edited'
    edited_doc: Optional[str] = None


# ============================================================================
# Workflow Models
# ============================================================================

@dataclass
class ErrorInfo:
    """Information about an error encountered during processing."""
    error_type: str
    stage: str  # 'analysis', 'context', 'generation', 'export'
    element_id: Optional[str]
    file_path: Optional[str]
    error_message: str
    timestamp: datetime
    recoverable: bool


@dataclass
class SessionStatusInfo:
    """Current status information for a documentation session."""
    stage: str  # 'analysis', 'context', 'generation', 'review', 'complete'
    progress_percent: float
    current_file: Optional[str] = None
    elements_processed: int = 0
    total_elements: int = 0


@dataclass
class DocumentationSession:
    """
    Complete documentation generation session.
    
    Tracks all state and results for a documentation workflow.
    """
    session_id: str
    file_paths: List[str]
    gap_report: Optional[GapReport] = None
    context_map: Optional[ContextMap] = None
    documentation_items: List[DocumentationItem] = field(default_factory=list)
    status: SessionStatusInfo = field(default_factory=lambda: SessionStatusInfo(
        stage="analysis",
        progress_percent=0.0
    ))
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)
    errors: List[ErrorInfo] = field(default_factory=list)


# ============================================================================
# Export Models
# ============================================================================

@dataclass
class ExportResult:
    """Results of exporting documentation."""
    success: bool
    format_type: str
    output_files: List[str]
    elements_exported: int
    elements_by_language: Dict[str, int]
    export_time_ms: float
    errors: List[str] = field(default_factory=list)


# ============================================================================
# Configuration Models
# ============================================================================

@dataclass
class ResourceLimits:
    """Resource limits for documentation generation."""
    max_concurrent_llm_requests: int = 5
    max_elements_per_batch: int = 10
    max_session_duration_minutes: int = 60
    max_file_size_mb: int = 10
    max_total_elements: int = 1000


@dataclass
class DocumentationConfig:
    """Configuration for documentation generation."""
    llm_model: str = "gemini-3-flash-preview"
    llm_temperature: float = 0.3
    llm_max_tokens: int = 2048
    quality_threshold: float = 70.0
    max_retries: int = 3
    retry_delay: float = 2.0
    batch_size: int = 10
    enable_caching: bool = True
    cache_ttl_hours: int = 24
    resource_limits: ResourceLimits = field(default_factory=ResourceLimits)
