from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from enum import Enum
import time

class TestType(Enum):
    UNIT = "unit"
    INTEGRATION = "integration"
    EDGE_CASE = "edge_case"

class TestFramework(Enum):
    PYTEST = "pytest"
    JEST = "jest"
    UNITTEST = "unittest"

@dataclass
class TestableElement:
    """Represents a code element (function/class) that can be tested."""
    element_id: str
    name: str
    element_type: str  # function, class, method
    file_path: str
    start_line: int
    end_line: int
    content: str
    complexity_score: float = 0.0
    has_existing_tests: bool = False
    dependencies: List[str] = field(default_factory=list)
    docstring: Optional[str] = None
    
    @property
    def key(self) -> str:
        """Unique key for the element"""
        return f"{self.file_path}:{self.name}"

@dataclass
class GeneratedTest:
    """Represents a test generated by the AI."""
    test_id: str
    target_element_id: str
    original_code: str  # The code being tested
    test_code: str
    test_type: str  # unit, integration, edge_case
    framework: str = "pytest"
    confidence_score: float = 0.0
    imports: List[str] = field(default_factory=list)
    explanation: Optional[str] = None
    status: str = "pending"  # pending, approved, rejected, edited

@dataclass
class TestResult:
    """Result of a test execution."""
    test_id: str
    file_path: str
    passed: bool
    output: str
    error_message: Optional[str] = None
    execution_time_ms: float = 0.0
    
@dataclass
class TestGenerationSession:
    """Tracks state of a test generation session."""
    session_id: str
    selected_files: List[str] = field(default_factory=list)
    identified_elements: Dict[str, TestableElement] = field(default_factory=dict)
    generated_tests: Dict[str, GeneratedTest] = field(default_factory=dict)
    test_results: Dict[str, TestResult] = field(default_factory=dict)
    start_time: float = field(default_factory=time.time)
    
    def get_pending_count(self) -> int:
        return sum(1 for t in self.generated_tests.values() if t.status == "pending")
        
    def get_approved_count(self) -> int:
        return sum(1 for t in self.generated_tests.values() if t.status == "approved")
